#!/bin/bash

wd=/var/lib/symbolics
cmd="DISPLAY=:1 ./genera  2>&1 > genera.log"
pidfile="$wd/genera.pid"
exec="$wd/genera"
sudo /sbin/start-stop-daemon --start --background --quiet --oknodo \
			--chdir "$wd" --exec "$exec" --startas /bin/bash -- -c "$cmd"

